// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunUyHaDXWqgHJ5Snqhh8xJAw5kFEuRqM',
    appId: '1:958789012571:web:49a5745550cbe96babc37e',
    messagingSenderId: '958789012571',
    projectId: 'tatalk-53ba7',
    authDomain: 'tatalk-53ba7.firebaseapp.com',
    storageBucket: 'tatalk-53ba7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPr4_r1HHS-hHW2wVUrfK_uiM4W2QnuVI',
    appId: '1:958789012571:android:151f6bfbd5c91804abc37e',
    messagingSenderId: '958789012571',
    projectId: 'tatalk-53ba7',
    storageBucket: 'tatalk-53ba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8utV5U5aQhs7q1aqs4d9k61Ph6cCJUM',
    appId: '1:958789012571:ios:9f0250d7a187f41aabc37e',
    messagingSenderId: '958789012571',
    projectId: 'tatalk-53ba7',
    storageBucket: 'tatalk-53ba7.firebasestorage.app',
    iosBundleId: 'com.example.chatdansosmed',
  );
}
